package laporan;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import simrskhanza.DlgCariBangsal;
import simrskhanza.DlgCariCaraBayar;

public class DlgYanmedSIRSTempatTidur extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private DlgCariCaraBayar penjab=new DlgCariCaraBayar(null,false);
    private DlgCariBangsal bangsal=new DlgCariBangsal(null,false);
    private int i=0;
    private StringBuilder htmlContent;
    ArrayList<Integer[]> dataSIRS = new ArrayList<Integer[]>();
    Map<String,ArrayList<Integer[]>> data = new HashMap<>();
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgYanmedSIRSTempatTidur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML.setDocument(doc);
        
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        BtnAll = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Laporan SIRS RL 1.3 Tempat Tidur ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50)));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi1.add(BtnAll);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(80, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#323232;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
            );
            bg.close();
            
            File f = new File("BulananHAIs.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));            
            bw.write(LoadHTML.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                        "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                            "<tr class='isi2'>"+
                                "<td valign='top' align='center'>"+
                                    "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                    akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                    akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+       
                                "</td>"+
                           "</tr>"+
                        "</table>")
            );
            bw.close();                         
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,Tgl2,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,Tgl1);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    prosesCari();
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed

        prosesCari();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            prosesCari();
        }else{
            Valid.pindah(evt, BtnPrint, BtnKeluar);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgYanmedSIRSTempatTidur dialog = new DlgYanmedSIRSTempatTidur(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.ScrollPane Scroll;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='4%' >KODE RS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='8%' >NAMA RS"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='4%' >BULAN</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='3%' >TAHUN</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='5%' >KAB/KOTA</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='4%' >KODE PROPINSI</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >NO</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='13%' >NAMA BANGSAL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >JUMLAH TT</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >VVIP</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >VIP</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >I</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >II</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >III</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' >KELAS KHUSUS</td>"+
                    "<td valign='middle' bgcolor='#FFFFFF' align='center' width='45%' ></td>"+
                "</tr>"
            );
            
            DecimalFormat df = new DecimalFormat("###.##");
            
            ps=koneksi.prepareStatement(
                    "SELECT b.nm_bangsal, COUNT(b.nm_bangsal) AS jml,\n" +
                    "SUM(CASE WHEN k.kelas = 'VVIP' THEN 1 ELSE 0 END) vvip, \n" +
                    "SUM(CASE WHEN k.kelas = 'VIP' THEN 1 ELSE 0 END) vip, \n" +
                    "SUM(CASE WHEN k.kelas = 'KELAS I' THEN 1 ELSE 0 END) i, \n" +
                    "SUM(CASE WHEN k.kelas = 'KELAS II' THEN 1 ELSE 0 END) ii, \n" +
                    "SUM(CASE WHEN k.kelas = 'KELAS III' THEN 1 ELSE 0 END) iii, \n" +
                    "SUM(CASE WHEN k.kelas NOT IN ('VVIP','VIP','KELAS I','KELAS II','KELAS III') THEN 1 ELSE 0 END) khusus\n" +
                    "FROM kamar k\n" +
                    "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal\n" +
                    "WHERE k.statusdata = '1'\n" +
                    "GROUP BY b.kd_bangsal");
            try {
                i=1;                     
                rs=ps.executeQuery();
//                System.out.println("yanmed ranap "+ps); 
                while(rs.next()){
//                    dataSIRS.add(new Integer[] {(rs.getInt("l")+rs.getInt("p")),rs.getInt("l"), rs.getInt("p")});
//                    data.put(rs.getString("kd_poli"), dataSIRS);
//                    int jumlah = rs.getInt("l") + rs.getInt("p");
                    htmlContent.append(                             
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>3573022</td>"+
                            "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
                            "<td valign='middle' align='center'>Agustus</td>"+
                            "<td valign='middle' align='left'>2022</td>"+
                            "<td valign='middle' align='center'>Kota Malang</td>"+
                            "<td valign='middle' align='center'>35prop</td>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("nm_bangsal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("jml")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("vvip")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("vip")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("i")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("ii")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("iii")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("khusus")+"</td>"+
                            "<td valign='middle' align='center'></td>"+
                        "</tr>"
                    ); 
                    i++;
                }
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>1</td>"+
//                        "<td valign='middle' align='center'>Penyakit Dalam</td>"+
//                        "<td valign='middle' align='center'>"+data.get("INT").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("INT").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("INT").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>2</td>"+
//                        "<td valign='middle' align='center'>Bedah</td>"+
//                        "<td valign='middle' align='center'>"+data.get("BED").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("BED").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("BED").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>3</td>"+
//                        "<td valign='middle' align='center'>Kesehatan Anak (Neonatal)</td>"+
//                        "<td valign='middle' align='center'>"+data.get("ANA").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("ANA").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("ANA").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>4</td>"+
//                        "<td valign='middle' align='center'>Kesehatan Anak Lainnya</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>5</td>"+
//                        "<td valign='middle' align='center'>Obstetri & Ginekologi (Ibu Hamil)</td>"+
//                        "<td valign='middle' align='center'>"+data.get("OBG").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("OBG").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("OBG").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>6</td>"+
//                        "<td valign='middle' align='center'>Obstetri & Ginekologi Lainnya</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>7</td>"+
//                        "<td valign='middle' align='center'>Keluarga Berencana</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>8</td>"+
//                        "<td valign='middle' align='center'>Bedah Saraf</td>"+
//                        "<td valign='middle' align='center'>"+data.get("BSY").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("BSY").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("BSY").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>9</td>"+
//                        "<td valign='middle' align='center'>Saraf</td>"+
//                        "<td valign='middle' align='center'>"+data.get("SAR").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("SAR").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("SAR").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>10</td>"+
//                        "<td valign='middle' align='center'>Jiwa</td>"+
//                        "<td valign='middle' align='center'>"+data.get("JIW").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("JIW").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("JIW").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>11</td>"+
//                        "<td valign='middle' align='center'>Napza</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>12</td>"+
//                        "<td valign='middle' align='center'>Psikologi</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>13</td>"+
//                        "<td valign='middle' align='center'>THT</td>"+
//                        "<td valign='middle' align='center'>"+data.get("THT").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("THT").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("THT").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>14</td>"+
//                        "<td valign='middle' align='center'>Mata</td>"+
//                        "<td valign='middle' align='center'>"+data.get("MAT").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("MAT").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("MAT").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>15</td>"+
//                        "<td valign='middle' align='center'>Kulit dan Kelamin</td>"+
//                        "<td valign='middle' align='center'>"+data.get("KLT").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("KLT").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("KLT").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>16</td>"+
//                        "<td valign='middle' align='center'>Gigi & Mulut</td>"+
//                        "<td valign='middle' align='center'>"+ (Integer.parseInt(data.get("BDM").get(0).toString()) + Integer.parseInt(data.get("BDM").get(0).toString()) + Integer.parseInt(data.get("GIG").get(0).toString()))+"</td>"+
//                        "<td valign='middle' align='center'>"+ (Integer.parseInt(data.get("BDM").get(1).toString()) + Integer.parseInt(data.get("BDM").get(1).toString()) + Integer.parseInt(data.get("GIG").get(1).toString()))+"</td>"+
//                        "<td valign='middle' align='center'>"+ (Integer.parseInt(data.get("BDM").get(2).toString()) + Integer.parseInt(data.get("BDM").get(2).toString()) + Integer.parseInt(data.get("GIG").get(2).toString()))+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>17</td>"+
//                        "<td valign='middle' align='center'>Geriatri</td>"+
//                        "<td valign='middle' align='center'>"+data.get("GER").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("GER").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("GER").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>18</td>"+
//                        "<td valign='middle' align='center'>Kardiologi</td>"+
//                        "<td valign='middle' align='center'>"+data.get("JAN").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("JAN").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("JAN").get(2).toString()+"</td>"+
//                    "</tr>"
//                );
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>19</td>"+
//                        "<td valign='middle' align='center'>Radiologi</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                );  
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>20</td>"+
//                        "<td valign='middle' align='center'>Bedah Orthopedi</td>"+
//                        "<td valign='middle' align='center'>"+data.get("ORT").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("ORT").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("ORT").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>21</td>"+
//                        "<td valign='middle' align='center'>Paru-paru</td>"+
//                        "<td valign='middle' align='center'>"+data.get("PAR").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("PAR").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("PAR").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>22</td>"+
//                        "<td valign='middle' align='center'>Kusta</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>23</td>"+
//                        "<td valign='middle' align='center'>Umum</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>24</td>"+
//                        "<td valign='middle' align='center'>Rawat Darurat</td>"+
//                        "<td valign='middle' align='center'>"+data.get("UGD").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("UGD").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("UGD").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>25</td>"+
//                        "<td valign='middle' align='center'>Rehabilitasi Medik</td>"+
//                        "<td valign='middle' align='center'>"+data.get("IRM").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("IRM").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("IRM").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>26</td>"+
//                        "<td valign='middle' align='center'>Akupungtur Medik</td>"+
//                        "<td valign='middle' align='center'>"+data.get("AKP").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("AKP").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("AKP").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>27</td>"+
//                        "<td valign='middle' align='center'>Konsultasi Gizi</td>"+
//                        "<td valign='middle' align='center'>"+data.get("GIZ").get(0).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("GIZ").get(1).toString()+"</td>"+
//                        "<td valign='middle' align='center'>"+data.get("GIZ").get(2).toString()+"</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>28</td>"+
//                        "<td valign='middle' align='center'>Day Care</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
//                htmlContent.append(                             
//                    "<tr class='isi'>"+
//                        "<td valign='middle' align='center'>3573022</td>"+
//                        "<td valign='middle' align='center'>RS Tk. II Dr. Soepraoen</td>"+
//                        "<td valign='middle' align='center'>Agustus</td>"+
//                        "<td valign='middle' align='left'>2022</td>"+
//                        "<td valign='middle' align='center'>Kota Malang</td>"+
//                        "<td valign='middle' align='center'>35prop</td>"+
//                        "<td valign='middle' align='center'>29</td>"+
//                        "<td valign='middle' align='center'>Lain-lain</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                        "<td valign='middle' align='center'>0</td>"+
//                    "</tr>"
//                ); 
                    
            } catch (Exception e) {
                System.out.println("laporan.YanmedRanap.prosesCari() : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            
            LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    public void isCek(){
        BtnPrint.setEnabled(akses.getbulanan_HAIs());
    }
    
}
