package laporan;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import simrskhanza.DlgCariBangsal;
import simrskhanza.DlgCariCaraBayar;

public class DlgYanmedRalan extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private DlgCariCaraBayar penjab=new DlgCariCaraBayar(null,false);
    private DlgCariBangsal bangsal=new DlgCariBangsal(null,false);
    private int i=0,jumlah1,jumlah2,pengunjung_mil_ad,pengunjung_pns_ad,pengunjung_kel_ad,pengunjung_mil_lain,pengunjung_pns_lain,pengunjung_kel_lain,
            pengunjung_dikma,pengunjung_taruna,pengunjung_bpjs,pengunjung_umum,total_jumlah1,
            kunjungan_mil_ad,kunjungan_pns_ad,kunjungan_kel_ad,kunjungan_mil_lain,
            kunjungan_pns_lain,kunjungan_kel_lain,kunjungan_dikma,kunjungan_taruna,kunjungan_bpjs,kunjungan_umum,total_jumlah2,
            rujukan, ranap, lainlain;
    private StringBuilder htmlContent;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgYanmedRalan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML.setDocument(doc);
        
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        BtnAll = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Laporan Rawat Jalan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50)));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi1.add(BtnAll);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(80, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#323232;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
            );
            bg.close();
            
            File f = new File("BulananHAIs.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));            
            bw.write(LoadHTML.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                        "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                            "<tr class='isi2'>"+
                                "<td valign='top' align='center'>"+
                                    "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                    akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                    akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+       
                                "</td>"+
                           "</tr>"+
                        "</table>")
            );
            bw.close();                         
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,Tgl2,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,Tgl1);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    prosesCari();
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed

        prosesCari();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            prosesCari();
        }else{
            Valid.pindah(evt, BtnPrint, BtnKeluar);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgYanmedRalan dialog = new DlgYanmedRalan(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.ScrollPane Scroll;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' rowspan='3'>No.</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='10%' rowspan='3'>Jenis Pelayanan Rawat Jalan</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='40%' colspan='10'>Jumlah Pengunjung</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='2%' rowspan='3'>JML</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='40%' colspan='10'>Jumlah Kunjungan</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='2%' rowspan='3'>JML</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='5%' colspan='3'>Tidak Lanjut Pelayanan</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' colspan='3'>AD</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' colspan='3'>Angkatan Lain</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Siswa Dikma</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Taruna</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>BPJS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Umum</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' colspan='3'>AD</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' colspan='3'>Angkatan Lain</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Siswa Dikma</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Taruna</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>BPJS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Umum</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Rujukan</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Rawat Inap</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Lain-Lain</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>MIL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>PNS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>KEL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>MIL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>PNS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>KEL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>MIL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>PNS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>KEL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>MIL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>PNS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>KEL</td>"+
                "</tr>" +
                "<tr class='isi'>"+
                    "<td valign='middle' align='center'>1</td>"+
                    "<td valign='middle' align='center'>2</td>"+
                    "<td valign='middle' align='center'>3</td>"+
                    "<td valign='middle' align='center'>4</td>"+
                    "<td valign='middle' align='center'>5</td>"+
                    "<td valign='middle' align='center'>6</td>"+
                    "<td valign='middle' align='center'>7</td>"+
                    "<td valign='middle' align='center'>8</td>"+
                    "<td valign='middle' align='center'>9</td>"+
                    "<td valign='middle' align='center'>10</td>"+
                    "<td valign='middle' align='center'>11</td>"+
                    "<td valign='middle' align='center'>12</td>"+
                    "<td valign='middle' align='center'>13</td>"+
                    "<td valign='middle' align='center'>14</td>"+
                    "<td valign='middle' align='center'>15</td>"+
                    "<td valign='middle' align='center'>16</td>"+
                    "<td valign='middle' align='center'>17</td>"+
                    "<td valign='middle' align='center'>18</td>"+
                    "<td valign='middle' align='center'>19</td>"+
                    "<td valign='middle' align='center'>20</td>"+
                    "<td valign='middle' align='center'>21</td>"+
                    "<td valign='middle' align='center'>22</td>"+
                    "<td valign='middle' align='center'>23</td>"+
                    "<td valign='middle' align='center'>24</td>"+
                    "<td valign='middle' align='center'>25</td>"+
                    "<td valign='middle' align='center'>26</td>"+
                    "<td valign='middle' align='center'>27</td>"+
                "</tr>"
            );
            ps=koneksi.prepareStatement(
                    "SELECT IFNULL(po.nm_poli,'null') as nm_poli, \n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND gt.nama_golongan = 'TNI AD' THEN 1 ELSE 0 END) pengunjung_mil_ad,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND gt.nama_golongan = 'PNS AD' THEN 1 ELSE 0 END) pengunjung_pns_ad,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%ANAK%' OR p.pekerjaan LIKE 'A/D%' OR p.pekerjaan LIKE 'I/D%' OR p.pekerjaan LIKE 'ISTRI%' OR p.pekerjaan LIKE 'I/S%' THEN 1 ELSE 0 END) pengunjung_kel_ad,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND gt.nama_golongan IN ('TNI AU','TNI AL') THEN 1 ELSE 0 END) pengunjung_mil_lain,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE 'PNS%' AND pekerjaan NOT LIKE 'PNS AD%' THEN 1 ELSE 0 END) pengunjung_pns_lain,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%ANAK%' OR p.pekerjaan LIKE 'A/D%' OR p.pekerjaan LIKE 'I/D%' OR p.pekerjaan LIKE 'ISTRI%' OR p.pekerjaan LIKE 'I/S%' THEN 1 ELSE 0 END) pengunjung_kel_lain,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%DIKMA%' THEN 1 ELSE 0 END) pengunjung_dikma,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%TARUNA%' THEN 1 ELSE 0 END) pengunjung_taruna,\n" +
                    "    SUM(CASE WHEN r.kd_pj IN ('A65', 'BPJ') AND r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat')  THEN 1 ELSE 0 END) pengunjung_bpjs,\n" +
                    "    SUM(CASE WHEN r.kd_pj NOT IN ('A65', 'BPJ') AND r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat')   THEN 1 ELSE 0 END) pengunjung_umum,\n" +
                    "SUM(CASE WHEN r.stts_daftar = 'Baru' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND  gt.nama_golongan = 'TNI AD' THEN 1 ELSE 0 END) kunjungan_mil_ad,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND gt.nama_golongan = 'PNS AD' THEN 1 ELSE 0 END) kunjungan_pns_ad,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%ANAK%' OR p.pekerjaan LIKE 'A/D%' OR p.pekerjaan LIKE 'I/D%' OR p.pekerjaan LIKE 'ISTRI%' OR p.pekerjaan LIKE 'I/S%' THEN 1 ELSE 0 END) kunjungan_kel_ad,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND gt.nama_golongan IN ('TNI AU','TNI AL') THEN 1 ELSE 0 END) kunjungan_mil_lain,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE 'PNS%' AND pekerjaan NOT LIKE 'PNS AD%' THEN 1 ELSE 0 END) kunjungan_pns_lain,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%ANAK%' OR p.pekerjaan LIKE 'A/D%' OR p.pekerjaan LIKE 'I/D%' OR p.pekerjaan LIKE 'ISTRI%' OR p.pekerjaan LIKE 'I/S%' THEN 1 ELSE 0 END) kunjungan_kel_lain,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%DIKMA%' THEN 1 ELSE 0 END) kunjungan_dikma,\n" +
                    "    SUM(CASE WHEN r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') AND p.pekerjaan LIKE '%TARUNA%' THEN 1 ELSE 0 END) kunjungan_taruna,\n" +
                    "    SUM(CASE WHEN r.kd_pj IN ('A65', 'BPJ') AND r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat') THEN 1 ELSE 0 END) kunjungan_bpjs,\n" +
                    "    SUM(CASE WHEN r.kd_pj NOT IN ('A65', 'BPJ') AND r.stts_daftar = 'Lama' AND r.status_lanjut = 'Ralan' AND stts IN ('Belum','Sudah','Berkas Diterima','Dirawat')   THEN 1 ELSE 0 END) kunjungan_umum,\n" +
                    "    SUM(CASE WHEN stts IN ('Dirujuk') THEN 1 ELSE 0 END) rujukan,\n" +
                    "    SUM(CASE WHEN stts IN ('Dirawat') AND r.status_lanjut = 'Ranap' THEN 1 ELSE 0 END) ranap,\n" +
                    "    SUM(CASE WHEN stts IN ('Batal','Meninggal','Pulang Paksa') THEN 1 ELSE 0 END) lainlain\n" +
                    "FROM reg_periksa r\n" +
                    "INNER JOIN poliklinik po ON po.kd_poli = r.kd_poli\n" +
                    "INNER JOIN pasien p ON p.no_rkm_medis = r.no_rkm_medis\n" +
                    "INNER JOIN pasien_tni pt ON pt.no_rkm_medis = p.no_rkm_medis\n" +
                    "INNER JOIN golongan_tni gt ON gt.id = pt.golongan_tni " +
                    "WHERE r.tgl_registrasi BETWEEN ? AND ?\n" +
                    "GROUP BY r.kd_poli");
            try {
                i=1;          
                pengunjung_mil_ad=0;pengunjung_pns_ad=0;pengunjung_kel_ad=0;pengunjung_mil_lain=0;pengunjung_pns_lain=0;pengunjung_kel_lain=0;
                pengunjung_dikma=0;pengunjung_taruna=0;pengunjung_bpjs=0;pengunjung_umum=0;total_jumlah1=0;
                kunjungan_mil_ad=0;kunjungan_pns_ad=0;kunjungan_kel_ad=0;kunjungan_mil_lain=0;kunjungan_pns_lain=0;kunjungan_kel_lain=0;
                kunjungan_dikma=0;kunjungan_taruna=0;kunjungan_bpjs=0;kunjungan_umum=0;total_jumlah2=0;
                rujukan=0;ranap=0;lainlain=0;
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                System.out.println("yanmed ralan "+ps);
                while(rs.next()){
                    int _pengunjung_bpjs = (rs.getInt("pengunjung_bpjs")-rs.getInt("pengunjung_mil_ad")-rs.getInt("pengunjung_pns_ad")-rs.getInt("pengunjung_kel_ad")-
                            rs.getInt("pengunjung_mil_lain")-rs.getInt("pengunjung_pns_lain")-rs.getInt("pengunjung_kel_lain")-rs.getInt("pengunjung_dikma")-rs.getInt("pengunjung_taruna"));
                    
                    int _kunjungan_bpjs = (rs.getInt("kunjungan_bpjs")-rs.getInt("kunjungan_mil_ad")-rs.getInt("kunjungan_pns_ad")-rs.getInt("kunjungan_kel_ad")-
                            rs.getInt("kunjungan_mil_lain")-rs.getInt("kunjungan_pns_lain")-rs.getInt("kunjungan_kel_lain")-rs.getInt("kunjungan_dikma")-rs.getInt("kunjungan_taruna"));
                    
                    jumlah1 = rs.getInt("pengunjung_mil_ad")+rs.getInt("pengunjung_pns_ad")+rs.getInt("pengunjung_kel_ad")+rs.getInt("pengunjung_mil_lain")+rs.getInt("pengunjung_pns_lain")+rs.getInt("pengunjung_kel_lain")+rs.getInt("pengunjung_dikma")+rs.getInt("pengunjung_taruna")+_pengunjung_bpjs+rs.getInt("pengunjung_umum");
                    jumlah2 = rs.getInt("kunjungan_mil_ad")+rs.getInt("kunjungan_pns_ad")+rs.getInt("kunjungan_kel_ad")+rs.getInt("kunjungan_mil_lain")+rs.getInt("kunjungan_pns_lain")+rs.getInt("kunjungan_kel_lain")+rs.getInt("kunjungan_dikma")+rs.getInt("kunjungan_taruna")+_kunjungan_bpjs+rs.getInt("kunjungan_umum");
                    
                    pengunjung_mil_ad=pengunjung_mil_ad+rs.getInt("pengunjung_mil_ad");
                    pengunjung_pns_ad=pengunjung_pns_ad+rs.getInt("pengunjung_pns_ad");
                    pengunjung_kel_ad=pengunjung_kel_ad+rs.getInt("pengunjung_kel_ad");
                    pengunjung_mil_lain=pengunjung_mil_lain+rs.getInt("pengunjung_mil_lain");
                    pengunjung_pns_lain=pengunjung_pns_lain+rs.getInt("pengunjung_pns_lain");
                    pengunjung_kel_lain=pengunjung_kel_lain+rs.getInt("pengunjung_kel_lain");

                    pengunjung_dikma=pengunjung_dikma+rs.getInt("pengunjung_dikma");
                    pengunjung_taruna=pengunjung_taruna+rs.getInt("pengunjung_taruna");
                    pengunjung_bpjs=pengunjung_bpjs+_pengunjung_bpjs;
                    pengunjung_umum=pengunjung_umum+rs.getInt("pengunjung_umum");
                    total_jumlah1=total_jumlah1+jumlah1;

                    kunjungan_mil_ad=kunjungan_mil_ad+rs.getInt("kunjungan_mil_ad");
                    kunjungan_pns_ad=kunjungan_pns_ad+rs.getInt("kunjungan_pns_ad");
                    kunjungan_kel_ad=kunjungan_kel_ad+rs.getInt("kunjungan_kel_ad");
                    kunjungan_mil_lain=kunjungan_mil_lain+rs.getInt("kunjungan_mil_lain");

                    kunjungan_pns_lain=kunjungan_pns_lain+rs.getInt("kunjungan_pns_lain");
                    kunjungan_kel_lain=kunjungan_kel_lain+rs.getInt("kunjungan_kel_lain");
                    kunjungan_dikma=kunjungan_dikma+rs.getInt("kunjungan_dikma");
                    kunjungan_taruna=kunjungan_taruna+rs.getInt("kunjungan_taruna");
                    kunjungan_bpjs=kunjungan_bpjs+_kunjungan_bpjs;
                    kunjungan_umum=kunjungan_umum+rs.getInt("kunjungan_umum");
                    total_jumlah2=total_jumlah2+jumlah2;

                    rujukan=rujukan+rs.getInt("rujukan");
                    ranap=ranap+rs.getInt("ranap");
                    lainlain=lainlain+rs.getInt("lainlain");
                    
                    htmlContent.append(                             
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("nm_poli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_mil_ad")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_pns_ad")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_kel_ad")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_mil_lain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_pns_lain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_kel_lain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_dikma")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_taruna")+"</td>"+
                            "<td valign='middle' align='center'>"+_pengunjung_bpjs+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("pengunjung_umum")+"</td>"+
                            "<td valign='middle' align='center'>"+jumlah1+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_mil_ad")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_pns_ad")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_kel_ad")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_mil_lain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_pns_lain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_kel_lain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_dikma")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_taruna")+"</td>"+
                            "<td valign='middle' align='center'>"+_kunjungan_bpjs+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kunjungan_umum")+"</td>"+
                            "<td valign='middle' align='center'>"+jumlah2+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("rujukan")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("ranap")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("lainlain")+"</td>"+
                        "</tr>"
                    ); 
                    i++;
                }
                htmlContent.append(                             
                    "<tr class='isi'>"+
                        "<td valign='middle' align='right' colspan='2'>Total :</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_mil_ad+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_pns_ad+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_kel_ad+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_mil_lain+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_pns_lain+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_kel_lain+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_dikma+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_taruna+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_bpjs+"</td>"+
                        "<td valign='middle' align='center'>"+pengunjung_umum+"</td>"+
                        "<td valign='middle' align='center'>"+total_jumlah1+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_mil_ad+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_pns_ad+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_kel_ad+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_mil_lain+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_pns_lain+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_kel_lain+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_dikma+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_taruna+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_bpjs+"</td>"+
                        "<td valign='middle' align='center'>"+kunjungan_umum+"</td>"+
                        "<td valign='middle' align='center'>"+total_jumlah2+"</td>"+
                        "<td valign='middle' align='center'>"+rujukan+"</td>"+
                        "<td valign='middle' align='center'>"+ranap+"</td>"+
                        "<td valign='middle' align='center'>"+lainlain+"</td>"+
                    "</tr>"
                ); 
            } catch (Exception e) {
                System.out.println("laporan.YanmedRalan.prosesCari() : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            
            LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    public void isCek(){
        BtnPrint.setEnabled(akses.getbulanan_HAIs());
    }
    
}
