package laporan;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import simrskhanza.DlgCariBangsal;
import simrskhanza.DlgCariCaraBayar;

public class DlgYanmedRujukanWatnap extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private DlgCariCaraBayar penjab=new DlgCariCaraBayar(null,false);
    private DlgCariBangsal bangsal=new DlgCariBangsal(null,false);
    private int i=0,totaljumlah=0,jumlah=0,mil_ad=0,mil_lain=0,non_dinas=0,jkd=0,umum=0,alasan_tempat=0,alasan_drahli=0,alasan_fasilitas=0,alasan_lainlain=0,
            rsgs=0,rsal=0,rssa=0,rspn=0,lavalette=0,rslain=0,parsial=0,penuh=0;
    private StringBuilder htmlContent;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgYanmedRujukanWatnap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML.setDocument(doc);
        
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        BtnAll = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Laporan Rujukan Watnap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50)));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi1.add(BtnAll);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(80, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#323232;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
            );
            bg.close();
            
            File f = new File("BulananHAIs.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));            
            bw.write(LoadHTML.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                        "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                            "<tr class='isi2'>"+
                                "<td valign='top' align='center'>"+
                                    "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                    akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                    akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+       
                                "</td>"+
                           "</tr>"+
                        "</table>")
            );
            bw.close();                         
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,Tgl2,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,Tgl1);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    prosesCari();
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed

        prosesCari();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            prosesCari();
        }else{
            Valid.pindah(evt, BtnPrint, BtnKeluar);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgYanmedRujukanWatnap dialog = new DlgYanmedRujukanWatnap(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.ScrollPane Scroll;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='1%' rowspan='3'>No.</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='15%' rowspan='3'>Bagian</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='12%' colspan='3'>BPJS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='4%' rowspan='3'>JKD</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='4%' rowspan='3'>Umum</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='4%' rowspan='3'>Jml</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='16%' colspan='4'>Alasan Dirujuk</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='24%' colspan='6'>Tujuan</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' width='8%' colspan='2'>Ket</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' colspan='2'>Dinas</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Non Dinas</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Tidak Ada Tempat</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Tidak Ada Dokter Ahli</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Tidak Ada Fasilitas</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Lain-lain</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>RSGS</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>RSAL</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>RSSA</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>RSPN</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>RS Lavalette</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Lain-lain</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Parsial</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center' rowspan='2'>Penuh</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>AD</td>"+
                    "<td valign='middle' bgcolor='#FFFAF8' align='center'>Angk. Lain</td>"+
                "</tr>" +
                "<tr class='isi'>"+
                    "<td valign='middle' align='center'>1</td>"+
                    "<td valign='middle' align='center'>2</td>"+
                    "<td valign='middle' align='center'>3</td>"+
                    "<td valign='middle' align='center'>4</td>"+
                    "<td valign='middle' align='center'>5</td>"+
                    "<td valign='middle' align='center'>6</td>"+
                    "<td valign='middle' align='center'>7</td>"+
                    "<td valign='middle' align='center'>8</td>"+
                    "<td valign='middle' align='center'>9</td>"+
                    "<td valign='middle' align='center'>10</td>"+
                    "<td valign='middle' align='center'>11</td>"+
                    "<td valign='middle' align='center'>12</td>"+
                    "<td valign='middle' align='center'>13</td>"+
                    "<td valign='middle' align='center'>14</td>"+
                    "<td valign='middle' align='center'>15</td>"+
                    "<td valign='middle' align='center'>16</td>"+
                    "<td valign='middle' align='center'>17</td>"+
                    "<td valign='middle' align='center'>18</td>"+
                    "<td valign='middle' align='center'>19</td>"+
                    "<td valign='middle' align='center'>20</td>"+
                "</tr>"
            );
            ps=koneksi.prepareStatement(
                    "SELECT b.nm_bangsal,\n" +
                    "	SUM(CASE WHEN gt.nama_golongan IN ('TNI AD','PNS AD') AND r.kd_pj IN ('A65', 'BPJ') AND r.status_lanjut = 'Ralan'  THEN 1 ELSE 0 END) mil_ad,\n" +
                    "	SUM(CASE WHEN gt.nama_golongan IN ('TNI AU','TNI AL') AND r.kd_pj IN ('A65', 'BPJ') AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) mil_lain,\n" +
                    "	SUM(CASE WHEN p.pekerjaan NOT LIKE '%AL%' OR p.pekerjaan NOT LIKE '%AU%' OR p.pekerjaan NOT LIKE '%AD%' OR p.pekerjaan NOT LIKE '%TNI%' AND r.kd_pj IN ('A65', 'BPJ') AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) non_dinas,\n" +
                    "	SUM(CASE WHEN r.kd_pj IN ('22', 'A78', 'A70', 'A77') AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) jkd,\n" +
                    "	SUM(CASE WHEN r.kd_pj IN ('A09') AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) umum,\n" +
                    "	SUM(CASE WHEN ru.keterangan LIKE '%tempat%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) alasan_tempat,\n" +
                    "	SUM(CASE WHEN ru.keterangan LIKE '%ahli%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) alasan_drahli,\n" +
                    "	SUM(CASE WHEN ru.keterangan LIKE '%fasilitas%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) alasan_fasilitas,\n" +
                    "	SUM(CASE WHEN ru.keterangan LIKE '%lain-lain%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) alasan_lainlain,\n" +
                    "	SUM(CASE WHEN ru.rujuk_ke LIKE '%gatot subroto%' OR ru.rujuk_ke LIKE '%rspad%' OR  ru.rujuk_ke LIKE '%rsgs%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) rsgs,\n" +
                    "	SUM(CASE WHEN ru.rujuk_ke LIKE '%rsal%' OR ru.rujuk_ke LIKE '%angkatan laut%' OR ru.rujuk_ke LIKE '%ramelan%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) rsal,\n" +
                    "	SUM(CASE WHEN ru.rujuk_ke LIKE '%rssa%' OR ru.rujuk_ke LIKE '%saiful anwar%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) rssa,\n" +
                    "	SUM(CASE WHEN ru.rujuk_ke LIKE '%panti nirmala%' OR ru.rujuk_ke LIKE '%rspn%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) rspn,\n" +
                    "	SUM(CASE WHEN ru.rujuk_ke LIKE '%lavalette%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) lavalette,\n" +
                    "	SUM(CASE WHEN ru.rujuk_ke NOT LIKE '%gatot subroto%' OR ru.rujuk_ke NOT LIKE '%rspad%' OR  ru.rujuk_ke NOT LIKE '%rsgs%' OR\n" +
                    "		ru.rujuk_ke NOT LIKE '%rsal%' OR ru.rujuk_ke NOT LIKE '%angkatan laut%' OR ru.rujuk_ke NOT LIKE '%ramelan%' OR\n" +
                    "		ru.rujuk_ke NOT LIKE '%rssa%' OR ru.rujuk_ke NOT LIKE '%saiful anwar%' OR\n" +
                    "		ru.rujuk_ke NOT LIKE '%panti nirmala%' OR ru.rujuk_ke NOT LIKE '%rspn%' OR\n" +
                    "		ru.rujuk_ke NOT LIKE '%lavalette%' AND r.status_lanjut = 'Ralan' \n" +
                    "	THEN 1 ELSE 0 END) rslain,\n" +
                    "	SUM(CASE WHEN ru.keterangan LIKE '%parsial%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) parsial,\n" +
                    "	SUM(CASE WHEN ru.keterangan LIKE '%penuh%' AND r.status_lanjut = 'Ralan' THEN 1 ELSE 0 END) penuh\n" +
                    "FROM rujuk ru\n" +
                    "INNER JOIN reg_periksa r ON r.no_rawat = ru.no_rawat\n" +
                    "INNER JOIN pasien p ON p.no_rkm_medis = r.no_rkm_medis\n" +
                    "INNER JOIN kamar_inap ki ON r.no_rawat = ki.no_rawat\n" +
                    "INNER JOIN kamar k ON k.kd_kamar = ki.kd_kamar\n" +
                    "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal\n" +
                    "LEFT JOIN pasien_tni pt ON pt.no_rkm_medis = p.no_rkm_medis\n" +
                    "LEFT JOIN golongan_tni gt ON gt.id = pt.golongan_tni\n" +
                    "WHERE ru.tgl_rujuk BETWEEN ? AND ?\n" +
                    "GROUP BY k.kd_bangsal");
            try {
                i=1;                     
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                while(rs.next()){
                    jumlah = (rs.getInt(2)+rs.getInt(3)+rs.getInt(4)+rs.getInt(5)+rs.getInt(6));
                    mil_ad=mil_ad + rs.getInt("mil_ad");
                    mil_lain=mil_lain + rs.getInt("mil_lain") ;
                    non_dinas=non_dinas + rs.getInt("non_dinas") ;
                    jkd=jkd +  rs.getInt("jkd");
                    umum=umum +  rs.getInt("umum");
                    alasan_tempat=alasan_tempat +  rs.getInt("alasan_tempat");
                    alasan_drahli=alasan_drahli +  rs.getInt("alasan_drahli");
                    alasan_fasilitas=alasan_fasilitas +  rs.getInt("alasan_fasilitas");
                    alasan_lainlain=alasan_lainlain +  rs.getInt("alasan_lainlain");
                    rsgs=rsgs +  rs.getInt("rsgs");
                    rsal=rsal +  rs.getInt("rsal");
                    rssa=rssa +  rs.getInt("rssa");
                    rspn=rspn +  rs.getInt("rspn");
                    lavalette=lavalette +  rs.getInt("lavalette");
                    rslain=rslain +  rs.getInt("rslain");
                    parsial=parsial +  rs.getInt("parsial");
                    penuh=penuh +  rs.getInt("penuh");
                    totaljumlah = totaljumlah + jumlah;
                    
                    htmlContent.append(                               
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_bangsal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("mil_ad")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("mil_lain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("non_dinas")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("jkd")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("umum")+"</td>"+
                            "<td valign='middle' align='center'>"+jumlah+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("alasan_tempat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("alasan_drahli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("alasan_fasilitas")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("alasan_lainlain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("rsgs")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("rsal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("rssa")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("rspn")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("lavalette")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("rslain")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("parsial")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("penuh")+"</td>"+
                        "</tr>"
                    ); 
                    i++;
                }
                htmlContent.append(                             
                    "<tr class='isi'>"+
                        "<td valign='middle' align='right' colspan='2'>Total :</td>"+
                        "<td valign='middle' align='center'>"+mil_ad+"</td>"+
                        "<td valign='middle' align='center'>"+mil_lain+"</td>"+
                        "<td valign='middle' align='center'>"+non_dinas+"</td>"+
                        "<td valign='middle' align='center'>"+jkd+"</td>"+
                        "<td valign='middle' align='center'>"+umum+"</td>"+
                        "<td valign='middle' align='center'>"+totaljumlah+"</td>"+
                        "<td valign='middle' align='center'>"+alasan_tempat+"</td>"+
                        "<td valign='middle' align='center'>"+alasan_drahli+"</td>"+
                        "<td valign='middle' align='center'>"+alasan_fasilitas+"</td>"+
                        "<td valign='middle' align='center'>"+alasan_lainlain+"</td>"+
                        "<td valign='middle' align='center'>"+rsgs+"</td>"+
                        "<td valign='middle' align='center'>"+rsal+"</td>"+
                        "<td valign='middle' align='center'>"+rssa+"</td>"+
                        "<td valign='middle' align='center'>"+rspn+"</td>"+
                        "<td valign='middle' align='center'>"+lavalette+"</td>"+
                        "<td valign='middle' align='center'>"+rslain+"</td>"+
                        "<td valign='middle' align='center'>"+parsial+"</td>"+
                        "<td valign='middle' align='center'>"+penuh+"</td>"+
                    "</tr>"
                ); 
            } catch (Exception e) {
                System.out.println("laporan.YanmedRujukanWatnap.prosesCari() : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            
            LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    public void isCek(){
        BtnPrint.setEnabled(akses.getbulanan_HAIs());
    }
    
}
